---
features:
  - |
    The new ``nova::compute::libvirt::virtlogd_config`` parameter has been
    added.

deprecations:
  - |
    The ``nova::compute::libvirt::virtlogd::config`` class has been deprecated
    in favor of ``nova::compute::libvirt::virtlogd_config``.
